### PR TITLE
updates

### PR DESCRIPTION
**Pull request by Peprah94**
# Why have changes been made?

I have made changes to three files. One has to do with selection of environmental covariates and the other has to do with the selection of focal taxon without going through the excel file. The last change has to setting the encoder for the api when working with windows device.

# What changes have been made?

-  pipeline/import/environmentalImport.R: I have added a line of code that makes the user select the environmental covariates without going through the excel file to make the changes.

- functions/importRedList.R: The the encoding does not work in windows. I have added lines of code that set the encoding if the system the pipeline is being run on is WINDOWS.

- pipeline/import/taxaImport.R: Similar to the environmental covariates, I have added lines of code that makes the user choose the taxa to run without going into the excel file to make changes.

- masterScript.R: Some changes showing how the three functions above works.

### CODE REVIEW

**Comment by RRTogunov** [comment]
Does this branch use the latest version of the main branch? If not, I'd definitely merge the main branch into this one first to make sure there are no conflicts.
The changes in functions/importRedList.R look good as well as first part of masterScript. 
But the edits in pipeline/import/environmentalImport.R and pipeline/import/taxaImport.R and lower half of masterScript may be outdated with the recent merge of the [Tidy_repo_structure](https://github.com/gjearevoll/BioDivMapping/pull/105) branch.

**Review by RRTogunov — CHANGES_REQUESTED** [review]
Does this branch use the latest version of the main branch? If not, I'd definitely merge the main branch into this one first to make sure there are no conflicts.
The changes in functions/importRedList.R look good as well as first part of masterScript. 
But the edits in pipeline/import/environmentalImport.R and pipeline/import/taxaImport.R and lower half of masterScript may be outdated with the recent merge of the [Tidy_repo_structure](https://github.com/gjearevoll/BioDivMapping/pull/105) branch.

**Comment by Peprah94** [comment]
The branch used the latest version of the main branch.

**Comment by RRTogunov** [comment]
a few changes required:
1. masterScript.R defines level, region, crs, and res on lines 26-32 and on 72-76 (same with scheduledDownload, waitForGbif, focalTaxonIndex, and myMesh). Also, definition of mesh on L95 in masterScript, has been integrated into L84 of environmentalImport.R. I think these are carryovers from previous version of masterScript.R
2. a)  also, in your edit to pipeline/import/environmentalImport.R, should "rep(TRUE, length(focalTaxonIndex))" be "rep(TRUE, length(environmentalCovariates))"?
2. b) (alternative to 2a), in both environmentalImport.R and taxaImport.R, I don't think you need to specify number of FALSE & TRUE; ie. you should be able to just have:
```
focalTaxon$include <- FALSE
focalTaxon$include[focalTaxon$taxa %in% focalTaxonIndex] <- TRUE
```
3. double-check this, I think your PR, wouldn't selectedParameters always be identical to environmentalCovariates (assuming user doesn't specify covariates that don't exist in parameters$parameters). If I'm not mistaken, couldn't selectedParameters be specified directly in masterScript? specifically,
L99 in masterScript.R would become:
```
selectedParameters <- c("aspect", 
                             "elevation", 
                             "precipitation", 
                             "temperature")
```
and L56-61 in environmentalImport.R would become:
```
if(!exists("selectedParameters ")){
 selectedParameters <- parameters$parameters[parameters$selected]
}
```
If you make these 3 changes and @samaperrin is happy, it should be good to merge.

Two general comments:
1. I agree, it should be easier to adjust things in the pipeline than is currently done; I just made an [issue](https://github.com/gjearevoll/BioDivMapping/issues/113#issue-2122941341) detailing thoughts and possible solutions.
2. Also agree that big-picture, it would be good to generalise specification of pipeline arguments within R and not necessarily rely on external CSVs and enable working exclusively in R. For example, allow users to provide either a file path (what is currently implemented) or formatted data.frame (more common workflow in other packages) for things like focalSpecies and environmental import. We should make this into an issue and discuss with @oharar and others about what we want the workflow to look like for users beyond this specific contract.

**Comment by samaperrin** [comment]
Yeah you've made some updates to an outdated version of the repo, some of these are made redundant by @RRTogunov 's recent updates. It might be worth checking out the latest version and then seeing what still needs to be updated.

**Pull request closed without merging**
